### ISSUE TITLE
Cool And Simple CSS Animations

### ISSUE THREAD

**Issue by KevinGuedes** [KevinGuedes/ghblog#25]
# CSS
A simple animation to translate an element on de y-axis:

```css
.card {
 transition: translate ease-in-out 100ms,
}

.card:hover {
    translate: 0 -5px;
}
```

And an aniamtion for scaling the element:

```css
.card:hover {
  scale: 1.01
}
```
